# Generated by Django 6.0.4 on 2026-04-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='ciudad',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='place',
            name='pais',
        ),
        migrations.AddField(
            model_name='place',
            name='km',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
