# Generated by Django 6.0.4 on 2026-05-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_rename_ciudad_place_ubicacion_remove_place_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='fecha_visita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lugares/'),
        ),
    ]
